//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSMac {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Data;
    using System;
    
    
    public partial class TableSchema : TableSchemaBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 7 ""
            this.Write("\nCreate Table ");
            
            #line default
            #line hidden
            
            #line 8 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.TableName ));
            
            #line default
            #line hidden
            
            #line 8 ""
            this.Write("\n(\n    ");
            
            #line default
            #line hidden
            
            #line 10 ""

        foreach (DataRow row in this.Mdata.Rows)
        {
        string type = (string)row["資料型態"];
        string fieldName = (string)row["欄位英文名稱"];
        string chineseFieldName = (string)row["欄位中文名稱"];
        string key = (string)row["Key"];
        string CanNull = (string)row["CanNull"];
    
            
            #line default
            #line hidden
            
            #line 19 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 19 ""
 if (key == "PK") { 
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 20 ""
 if (type == "uniqueidentifier") { 
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( fieldName ));
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write(" UNIQUEIDENTIFIER DEFAULT NEWID(),\n    CONSTRAINT PK_");
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.TableName ));
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(" PRIMARY KEY CLUSTERED(");
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( fieldName ));
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write("),\n");
            
            #line default
            #line hidden
            
            #line 23 ""
 } else if (type == "int") { 
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( fieldName ));
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write(" Int Not Null Identity(1,1),\n    CONSTRAINT PK_");
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.TableName ));
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write(" PRIMARY KEY CLUSTERED(");
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( fieldName ));
            
            #line default
            #line hidden
            
            #line 25 ""
            this.Write("),\n");
            
            #line default
            #line hidden
            
            #line 26 ""
 } 
            
            #line default
            #line hidden
            
            #line 27 ""
 } else { 
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( fieldName ));
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( type ));
            
            #line default
            #line hidden
            
            #line 28 ""
 if (( type == "decimal") || ( type == "varchar") || ( type == "nvarchar")) { 
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( row["長度"] ));
            
            #line default
            #line hidden
            
            #line 29 ""
            this.Write(")");
            
            #line default
            #line hidden
            
            #line 29 ""
 } 
            
            #line default
            #line hidden
            
            #line 30 ""
 if (CanNull == "Y") { 
            
            #line default
            #line hidden
            
            #line 31 ""
            this.Write(" Null ");
            
            #line default
            #line hidden
            
            #line 31 ""
 } 
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(",\n    ");
            
            #line default
            #line hidden
            
            #line 33 ""
 }} 
            
            #line default
            #line hidden
            
            #line 34 ""
            this.Write(")\n\n--增加欄位說明\n    ");
            
            #line default
            #line hidden
            
            #line 37 ""

        foreach (DataRow row in this.Mdata.Rows)
        {
        string type = (string)row["資料型態"];
        string fieldName = (string)row["欄位英文名稱"];
        string chineseFieldName = (string)row["欄位中文名稱"];
        string key = (string)row["Key"];
    
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write("\nEXEC sys.sp_addextendedproperty\n    @name = N\'MS_Description\'\n    ,@value = N\'");
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( chineseFieldName ));
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write("\'\n    ,@level0type = N\'SCHEMA\'\n    ,@level0name = N\'ERP\'\n    ,@level1type = N\'TAB" +
                    "LE\'\n    ,@level1name = N\'");
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.TableName ));
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write("\'\n    ,@level2type = N\'COLUMN\'\n    ,@level2name = N\'");
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( fieldName ));
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write("\'\n    ");
            
            #line default
            #line hidden
            
            #line 55 ""
 } 
            
            #line default
            #line hidden
            
            #line 56 ""
            this.Write("    ");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class TableSchemaBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
